### ISSUE TITLE
EPIC: Production level documentation

### ISSUE THREAD

**Issue by sayantani11** [kubernetes-sigs/cluster-api-provider-gcp#451]
/kind documentation

**Describe the solution you'd like**
Currently our project requires a lot of addition to the docs. I have made a list of few topics that we could add for better understanding of the project.

- [ ] Identity and Access Management (IAM) : Administer and authorize who can take  action on resources
https://cloud.google.com/iam/docs/overview
https://cloud.google.com/resource-manager/docs/access-control-org
https://cloud.google.com/iam/docs/tags-access-control
- [ ] Service Accounts: Creation of service account and IAM management
https://cloud.google.com/iam/docs/service-accounts
https://cloud.google.com/iam/docs/workload-identity-federation
- [x] Persistent Disks for VMs provisioned in GCP
- [ ] API Endpoint Groups(Zonal & Internet / Internal & External) : Configure load balancer and IP
https://cloud.google.com/load-balancing/docs/negs
https://cloud.google.com/load-balancing/docs/load-balancing-overview
https://cloud.google.com/load-balancing/docs
- [ ] Google Cloud Instance Group : MachinePool using MIGS (Requires GATES)
- [ ] VM identity: describes the available identities that be configured on GCP
https://cloud.google.com/compute/docs/instances/access-overview
https://cloud.google.com/compute/docs/instances/windows/generating-credentials
- [ ] Workload identity: https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity
Related to the VM identity
- [x] Flannel: Using Flannel as a CNI solution
- [ ] ipV6: Creating ipV6 enabled clusters using CAPG
https://cloud.google.com/compute/docs/ip-addresses/configure-ipv6-address
- [ ] Creating gpu enabled clusters with CAPG:
https://cloud.google.com/dataproc/docs/concepts/compute/gpus
- [ ] Troubleshooting:  Common issues Users might run on to using CAPG
- [x] Preemptible VM instances: users to reduce the costs of their compute resources
https://cloud.google.com/compute/docs/instances/preemptible
- [ ] Cloud provider : To deploy a cluster using external cloud provider
- [ ] Custom private DNS zone name: DNS zone name to a custom value and availability of 8.8.8.8
- [ ] Alias IP: attach a secondary IP range from the GCPCluster subnet into the GCPMachine instance network 
- [ ] SSH access: https://cloud.google.com/solutions/connecting-securely

**Comment by budhirajamadhav** [comment]
Hi @sayantani11, Can I help with this?

**Comment by mehabhalodiya** [comment]
@sayantani11 I would like to give it a try. Can you help me to get started?

**Comment by sayantani11** [comment]
@mehabhalodiya Yes definitely, you can pick any one of the topics you would like to work upon & try going through the links attached to get some idea about the topic. After that you can make an issue with a readme file on the following topic related to it's use on CAPG, and add the cluster-template(if any) in the template folder. For a better understanding of how it's done, you can look at the docs in CAPZ(cluster-api-provider-azure). And for any further issues you can reach out to me on Slack.

**Comment by sayantani11** [comment]
lifecycle/frozen

**Comment by swarren83** [comment]
Need to update the [config/default/credentials.yaml](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/19299debddd5ba1c6bcd36c6216c9e1077c524a9/config/default/credentials.yaml#L5) to reflect `data.credentials` as the proper way to setup the secret.  The code is looking for `credentials` key in the secret.
